# Brian Burns
# Deploy dotnet project to Azure Functions

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run dotnet restore'
  inputs:
    command: 'restore'
    projects: 'ContactMe.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: 'ContactMe.csproj'
    custom: 'clean'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Run dotnet build'
  inputs:
    command: 'build'
    projects: 'ContactMe.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'ContactMe.csproj'
    arguments: '--configuration Release'
- task: CopyFiles@2
  displayName: 'Copy files to staging'
  inputs:
    SourceFolder: 'bin/Release/netcoreapp2.1/publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: ArchiveFiles@2
  displayName: 'Zip files for deployment'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
- task: AzureFunctionApp@1
  displayName: 'Deploy to Azure Functions'
  inputs:
    azureSubscription: 'Visual Studio Enterprise(bc7bc02b-bf19-4ea1-bee5-af7cbceab2c9)'
    appType: 'functionApp'
    appName: 'brnbrns'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    deploymentMethod: 'auto'
- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'GitHub'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    assets: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    addChangeLog: true
