# Brian Burns
# Deploy dotnet project to Azure Functions

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetAuthenticate@1
  displayName: 'Authenticate Nuget Feed'
- task: UseDotNet@2
  displayName: 'Use .NET 8'
  inputs:
    packageType: 'sdk'
    version: '8.x'
- task: DotNetCoreCLI@2
  displayName: 'Run dotnet restore'
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    arguments: '--no-cache --configfile nuget.config'
- task: DotNetCoreCLI@2
  displayName: 'Run dotnet clean'
  inputs:
    command: 'custom'
    custom: 'clean'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Run dotnet build'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
- task: ArchiveFiles@2
  displayName: 'Archive build'
  inputs:
    rootFolderOrFile: 'bin/Release/net8.0'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: 'bin/publish.zip'
    replaceExistingArchive: true
- task: AzureFunctionApp@1
  displayName: 'Deploy to Azure Functions'
  inputs:
    azureSubscription: 'bc7bc02b-bf19-4ea1-bee5-af7cbceab2c9 - Website'
    appType: 'functionApp'
    appName: 'brnbrns'
    package: 'bin/publish.zip'
    deploymentMethod: 'auto'
- task: GitHubRelease@1
  displayName: 'Mark release on GitHub'
  inputs:
    gitHubConnection: 'github.com_brnbrns'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    assets: 'bin/Release/net8.0/publish.zip'
    addChangeLog: true
